### ISSUE TITLE
Regression on map rendering

### ISSUE THREAD

**Issue by nicopace** [ConservationMetrics/gc-explorer#690]
A map used to work before, now it doesn't.
Details in https://github.com/ConservationMetrics/gc-programs/issues/238

The data is fetched from database properly.

**Comment by rudokemper** [comment]
@conservationtimothy can you take a look next week?

**Comment by rudokemper** [comment]
Console logs (this is for `MapView`)

```
installHook.js:1 Error: layers.data-layer-polygon.filter[2][2]: expected one of [Point, LineString, Polygon], "MultiPolygon" found
    at le (CtdPhxkR.js:18:15842)
    at Ds (CtdPhxkR.js:18:218908)
    at Proxy._validate (CtdPhxkR.js:18:280983)
    at Proxy.addLayer (CtdPhxkR.js:18:261410)
    at Proxy.addLayer (CtdPhxkR.js:3013:1009)
    at _ (m69Tqk1Q.js:11:6381)
    at D (m69Tqk1Q.js:11:8057)
    at Map.<anonymous> (m69Tqk1Q.js:11:4299)
    at Map.fire (CtdPhxkR.js:11:28551)
    at Map._render (CtdPhxkR.js:3013:12511)
```

Looks like a regression introduced by https://github.com/ConservationMetrics/gc-explorer/pull/654. Should be an easy fix:

### ChatGPT

Mapbox’s `$type` filter **does not expose `MultiPolygon` as a separate type**. It only accepts:

`Point`, `LineString`, or `Polygon`.

A GeoJSON `MultiPolygon` is treated as `"Polygon"` for filtering purposes. Same idea for `MultiLineString` → `"LineString"` and `MultiPoint` → `"Point"`. ([[Mapbox](https://docs.mapbox.com/style-spec/reference/expressions/?utm_source=chatgpt.com)][1])

So just do:

```js
map.value.addLayer({
  id: "data-layer-polygon",
  type: "fill",
  source: "data-source",
  filter: ["==", "$type", "Polygon"],
});
```

That will match **both `Polygon` and `MultiPolygon` GeoJSON features**.

So your current:

```js
filter: [
  "any",
  ["==", "$type", "Polygon"],
  ["==", "$type", "MultiPolygon"],
],
```

fails at style validation because `"MultiPolygon"` is literally not an allowed `$type` value.

Mapbox basically normalizes the `Multi*` geometries to their singular geometry family for style expressions. ([[Mapbox](https://docs.mapbox.com/style-spec/reference/expressions/?utm_source=chatgpt.com)][1])

[1]: https://docs.mapbox.com/style-spec/reference/expressions/?utm_source=chatgpt.com "Expressions | Mapbox Style Spec | Mapbox Docs | Mapbox"

### Let's add tests to cover these cases!
